#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scala-maven-plugin
Version  : 3.4.4
Release  : 1
URL      : https://github.com/davidB/scala-maven-plugin/archive/3.4.4.tar.gz
Source0  : https://github.com/davidB/scala-maven-plugin/archive/3.4.4.tar.gz
Source1  : https://repo.maven.apache.org/maven2/net/alchim31/maven/scala-maven-plugin/3.4.4/scala-maven-plugin-3.4.4.jar
Source2  : https://repo.maven.apache.org/maven2/net/alchim31/maven/scala-maven-plugin/3.4.4/scala-maven-plugin-3.4.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Unlicense

%description
# Scala Maven Plugin
[![Build Status](https://travis-ci.org/davidB/scala-maven-plugin.svg?branch=master)](https://travis-ci.org/davidB/scala-maven-plugin)

%prep

%build

%install

%files
%defattr(-,root,root,-)
