#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scala-maven-plugin
Version  : 3.4.4
Release  : 2
URL      : https://github.com/davidB/scala-maven-plugin/archive/3.4.4.tar.gz
Source0  : https://github.com/davidB/scala-maven-plugin/archive/3.4.4.tar.gz
Source1  : https://repo.maven.apache.org/maven2/net/alchim31/maven/scala-maven-plugin/3.4.4/scala-maven-plugin-3.4.4.jar
Source2  : https://repo.maven.apache.org/maven2/net/alchim31/maven/scala-maven-plugin/3.4.4/scala-maven-plugin-3.4.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Unlicense
Requires: mvn-scala-maven-plugin-data = %{version}-%{release}

%description
# Scala Maven Plugin
[![Build Status](https://travis-ci.org/davidB/scala-maven-plugin.svg?branch=master)](https://travis-ci.org/davidB/scala-maven-plugin)

%package data
Summary: data components for the mvn-scala-maven-plugin package.
Group: Data

%description data
data components for the mvn-scala-maven-plugin package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.4.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.4.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.4.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.4.4


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.4.4/scala-maven-plugin-3.4.4.jar
/usr/share/java/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.4.4/scala-maven-plugin-3.4.4.pom
